spring:
  application:
    name: Microservices-APIGateway

  data:
    mongodb:
      uri: mongodb://localhost:27017/authdb

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      default-filters:
        - PreserveHostHeader
        - name: JWTAuthFilter

      routes:
        - id: flight-service
          uri: lb://MICROSERVICE-FLIGHTSERVICE
          predicates:
            - Path=/microservice-flightservice/**
          filters:
            - StripPrefix=1

        - id: booking-service
          uri: lb://MICROSERVICE-BOOKINGSERVICE
          predicates:
            - Path=/microservice-bookingservice/**
          filters:
            - StripPrefix=1

      globalcors:
        add-to-simple-url-handler-mapping: true

server:
  port: 8091

jwt:
  secret: ThisIsAStrongJwtSecretKeyWithAtLeast64CharactersLengthForHS512Algorithm
  expirationMs: 86400000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka/
