spring:
  application:
    name: MICROSERVICE-BOOKINGSERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/bookingmicroservicedb

  jackson:
    serialization:
      indent_output: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: booking-email-group
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.micro.booking.event.BookingEvent
        spring.json.use.type.headers: false

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka/

resilience4j:
  circuitbreaker:
    instances:
      MICROSERVICE-FLIGHTSERVICE:
        slidingWindowSize: 3
        failureRateThreshold: 10
        waitDurationInOpenState: 5
        registerHealthIndicator: true

mail:
  host: localhost
  port: 1025
  properties:
    mail:
      smtp:
        auth: false
        starttls:
          enable: false

flight:
  service:
    url: http://localhost:8081/
